name: Package and release (CF)

on:
  workflow_dispatch: {}

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}

    steps:
      - name: Clone project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and distribute
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
        uses: McTalian/wow-build-tools@v1-beta
        with:
          args: -t ./DeviceLayoutPreset -r ./.release
