name: Update TOC Interface version(s)

on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * *

permissions:
  contents: write
  pull-requests: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Update TOC Interface version
        uses: Mctalian/toc-interface-updater@v1
        with:
          flavor: retail
          ptr: true

      - name: Create pull request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_PAT }}
          title: "build(toc): updates supported interface versions"
          body: |
            ## Requirements

            - [ ] Download test package in the comments below
            - [ ] Test for all applicable game clients
              - [ ] Retail
              - [ ] Retail PTR

            ----------------------------------------------------
            _This PR was automatically created to update the supported interface versions in DeviceLayoutPreset.toc._
          commit-message: "build(toc): updates supported interface versions"
          branch: interface-version
          delete-branch: true
